#include "config.h"

const float SPEED_PRESETS_RPM[] = CONFIG_SPEED_PRESETS_RPM;
const uint16_t RUN_CURRENT_MA[] = CONFIG_RUN_CURRENT_MA;
const uint8_t STALL_GUARD_THRESHOLDS[] = CONFIG_STALL_GUARD_THRESHOLDS;
const unsigned long STALL_DIAG_DEBOUNCE_MS[] = CONFIG_STALL_DIAG_DEBOUNCE_MS;
const size_t SPEED_PRESET_COUNT = sizeof(SPEED_PRESETS_RPM) / sizeof(SPEED_PRESETS_RPM[0]);
